
export default {
    "FETCH_CITY_REQUEST": "FETCH_CITY_REQUEST",
    "FETCH_CITY_FAILURE": "FETCH_CITY_FAILURE",
    "FETCH_CITY_SUCCESS": "FETCH_CITY_SUCCESS",
    "FETCH_MAP_REQUEST": "FETCH_MAP_REQUEST",
    "FETCH_MAP_FAILURE": "FETCH_MAP_FAILURE",
    "FETCH_MAP_SUCCESS": "FETCH_MAP_SUCCESS",
    "FETCH_MAP_CANCEL_REQUEST": "FETCH_MAP_CANCEL_REQUEST",
    "FETCH_MAP_CANCEL_REQUEST_SUCCESS": "FETCH_MAP_CANCEL_REQUEST_SUCCESS",
    "SEARCH_CITY_REQUEST": "SEARCH_CITY_REQUEST",
    "SEARCH_CITY_FAILURE": "SEARCH_CITY_FAILURE",
    "SEARCH_CITY_SUCCESS": "SEARCH_CITY_SUCCESS",
    "SET_SEARCH_CITY": "SET_SEARCH_CITY",
    "SET_SEARCH_COUNTRY": "SET_SEARCH_COUNTRY"
}